### PR TITLE
fixed opened issues to stabilize buffalo v1

### LINKED ISSUE #20: Pluralization and capitalization issues
`Pluralize()` should in theory pluralize a name while maintaining the cases. For example, `FooBar -> FooBars`.

However, there are a few cases where the pluralization produces unintentional lowercasing.

1. `Half -> halves`
    It seems that when the whole word matches an item in the `singularToPlural` map, the entire word gets converted in lowercase. On the contrary, this seems to behave correctly when a singular word is attached to another one, such as the case of `LemonHalf -> LemonHalves`.

2. `SmartPerson -> Smartpeople`
    It seems that when the suffix matches one of the `pluralRules`, the entire matched portion remains lowercase.

3. `SuperbOx -> Superboxes`
    It seems that camel-casing is not respected for breaking up words. ~In fact, the `pluralRules` seem to be applied first (`box -> boxes`) before the `singularToPlural` rules (`ox -> oxen`).~ In fact, it seems that when `ox` is attached to another word, it will never be changed to `oxen` (example: `big_ox -> big_oxes`).

Overall, having consistent behavior here is important as this package is used by `gobuffalo/pop` for auto-generating table names from camel-case structs. Happy to help discuss potential solutions!

### LINKED ISSUE #37: Generating a "pepsi" resource doesn't produce the desired outcome
### Description

When I try to generate a "pepsi" resource in a new buffalo app, the generator sometimes generates the proper names "pepsi/pepsis", and sometimes it generates "pepse/pepses".

METHOD | PATH | NAME | HANDLER
-- | -- | -- | --
GET | / | rootPath | coke/actions.HomeHandler
GET | /pepsis/ | pepsisPath | coke/actions.PepsisResource.List
POST | /pepsis/ | pepsisPath | coke/actions.PepsisResource.Create
GET | /pepsis/new/ | newPepsisPath | coke/actions.PepsisResource.New
GET | /pepsis/{pepse_id}/ | pepsePath | coke/actions.PepsisResource.Show
PUT | /pepsis/{pepse_id}/ | pepsePath | coke/actions.PepsisResource.Update
DELETE | /pepsis/{pepse_id}/ | pepsePath | coke/actions.PepsisResource.Destroy
GET | /pepsis/{pepse_id}/edit/ | editPepsePath | coke/actions.PepsisResource.Edit

These inconsistencies are also present in the code of the generated actions, for example:
```
// List gets all Pepsis. This function is mapped to the path
// GET /pepsis
func (v PepsisResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  pepses := &models.Pepsis{}
```

### Steps to Reproduce the Problem

  1. Generate a new buffalo app with `buffalo new dummyapp`, and set it up
  2. Inside your new app's folder run `buffalo generate resource pepsi`
  3. Check the generated code, or start your app in development mode, and try to create a new pepsi entry

### Expected Behaviour

"Pepsi" is a weird word, but pluralizing it does make sense, in my opinion, probably as "pepsis", but in any case, I would expect the generator to produce consistent naming and functional codde.

### Actual Behaviour

The naming is inconsistent and some routes are broken.

### Info

Please run `buffalo info` and paste the information below where it says "PASTE_HERE".

<details>

```
-> Go: Checking installation
✓ The `go` executable was found on your system at: /snap/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.13.4, meets the minimum requirements.

-> Go: Checking GOPATH
✓ You are using Go Modules, so no need to worry about the GOPATH.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /home/mladen/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /home/mladen/.nvm/versions/node/v13.5.0/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v13.5.0, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /home/mladen/.nvm/versions/node/v13.5.0/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.13.7, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /home/mladen/.nvm/versions/node/v13.5.0/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.21.1, meets the minimum requirements.

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
✓ The `mysql` executable was found on your system at: /usr/bin/mysql

-> MySQL: Checking minimum version requirements
✓ Your version of MySQL, 14.14, meets the minimum requirements.

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.22.0, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /usr/local/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.15.3, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /home/mladen/Projects/BuffaloTest/coke
Root        /home/mladen/Projects/BuffaloTest/coke
GoPath      /home/mladen/go
PackagePkg  coke
ActionsPkg  coke/actions
ModelsPkg   coke/models
GriftsPkg   coke/grifts
WithModules true
Name        coke
Bin         bin/coke
VCS         git
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack -p --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "coke"
bin = "bin/coke"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop"

-> Buffalo: go.mod
module coke

go 1.13

require (
	github.com/gobuffalo/buffalo v0.15.3
	github.com/gobuffalo/buffalo-pop v1.23.1
	github.com/gobuffalo/envy v1.8.1
	github.com/gobuffalo/mw-csrf v0.0.0-20190129204204-25460a055517
	github.com/gobuffalo/mw-forcessl v0.0.0-20180802152810-73921ae7a130
	github.com/gobuffalo/mw-i18n v0.0.0-20190129204410-552713a3ebb4
	github.com/gobuffalo/mw-paramlogger v0.0.0-20190129202837-395da1998525
	github.com/gobuffalo/packr/v2 v2.7.1
	github.com/gobuffalo/pop v4.13.1+incompatible
	github.com/gobuffalo/suite v2.8.2+incompatible
	github.com/gobuffalo/validate v2.0.3+incompatible
	github.com/gofrs/uuid v3.2.0+incompatible
	github.com/markbates/grift v1.5.0
	github.com/stretchr/testify v1.4.0
	github.com/unrolled/secure v0.0.0-20190103195806-76e6d4e9b90c
)

```

</details>

### PR DESCRIPTION
**Pull request by sio4**
as a follow-up for https://github.com/gobuffalo/buffalo/issues/2306, check and fix opened issues:

* fixed #37 by removing suffix rule of "pse" to "psis"
* fixed #20 (support pluralizing/singularizing for capitalized strings)
* ported #29 (multi-word support for pluralization) to singularize function
* added test case for #33
* updated module dependencies.

### CODE REVIEW

File: custom_data.go [hunk 1]
```diff
@@ -75,6 +76,10 @@ func LoadInflections(r io.Reader) error {
 	defer singularMoot.Unlock()
 
 	for s, p := range m {
+		if strings.Contains(s, " ") || strings.Contains(p, " ") {
```
Comment (sio4) [inline custom_data.go:79]: Flect supports parts of ident, so multi-word inflection doesn't make sense and it will cause unexpected results

File: flect_test.go [hunk 2]
```diff
@@ -16,8 +16,8 @@ type tt struct {
 func Test_LoadInflections(t *testing.T) {
 	r := require.New(t)
 	m := map[string]string{
-		"beatle": "the beatles",
```
Comment (sio4) [inline flect_test.go:19]: This is one example of the bad usage of Flect that support parts. "the beatles" will be parsed as "the" + "beatles" and singularize and pluralize function will only see the last part, "beatles", and the result of singularization for "the beatles" will always have "the" part.

File: plural_rules.go [hunk 3]
```diff
@@ -56,7 +57,6 @@ var singleToPlural = map[string]string{
 	"ellipsis":    "ellipses",
 	"equipment":   "equipment",
 	"erratum":     "errata",
-	"faux pas":    "faux pas",
```
Comment (sio4) [inline plural_rules.go:59]: again, Flect uses parts and this will not work correctly if functions properly support parts. previously, singularize function ignored multi-word strings but now we fixed that.

Like this example, the parts supporting has some weak point that cannot support this kind of thing, but I believe it is more flexible and useful for Buffalo.

File: plural_rules.go [hunk 4]
```diff
@@ -225,7 +225,6 @@ var singularToPluralSuffixList = []singularToPluralSuffix{
 	{"ode", "odes"},
 	{"ofe", "oves"},
 	{"pfe", "pves"},
-	{"pse", "psis"},
```
Comment (sio4) [inline plural_rules.go:228]: cannot find an example of this type of transformation while "pse" to "pses" is common.

File: plural_rules.go [hunk 5]
```diff
@@ -195,7 +196,6 @@ var singularToPluralSuffixList = []singularToPluralSuffix{
 	{"oose", "eese"},
 	{"ouse", "ouses"},
 	{"ovum", "ova"},
-	{"rion", "ria"},
```
Comment (sio4) [inline plural_rules.go:198]: it also not always correct, or it seems like the case of "~rions" is more popular.

File: plural_rules.go [hunk 6]
```diff
@@ -157,9 +159,7 @@ type singularToPluralSuffix struct {
 }
 
 var singularToPluralSuffixList = []singularToPluralSuffix{
-	{"iterion", "iteria"},
 	{"campus", "campuses"},
-	{"genera", "genus"},
```
Comment (sio4) [inline plural_rules.go:162]: reversed.
